---
# This playbook contains Mod Security installation/configuration for Apache.

- name: Create Mod Security temp directory
  file: 
    path: "{{ mod_security_unzip_dir }}"
    state: directory
  
- name: Unzip Mod Security archive
  unarchive: 
    src: "{{ mod_security_tarball_name }}"
    dest: "{{ mod_security_unzip_dir }}/"
  
- name: Autogenerate Mod Security
  shell: cd {{ mod_security_dir }} && ./autogen.sh 
 
- name: Configure Mod Security
  shell: cd {{ mod_security_dir }} && CFLAGS=-I/usr/include/libxml2 && ./configure --with-apxs={{ apache_home }}/bin/apxs 
  
- name: Make & Make install Mod Security
  shell: cd {{ mod_security_dir }} && make && make install 
  
- name: Delete Mod Security temp directory
  file: 
    path: "{{ mod_security_unzip_dir }}"
    state: absent 
  
- name: Create the log directory for Mod Security
  file: 
    path: "{{ mod_security_logs_dir }}"
    state: directory
    
- name: Create the configuration directory for Mod Security
  file: 
    path: "{{ mod_security_conf_dir }}"
    state: directory    
  
- name: Copy Mod Security library into Apache module directories
  shell: cp /usr/local/modsecurity/lib/mod_security2.so {{ apache_home }}/modules/

- name: Deploy Mod Security configuration files
  template: 
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    force: "{{item.force}}"
  with_items: "{{ mod_security_conf_files }}"