---
- hosts: all
  vars_files:
    - "password/password-{{env}}.yml"
  become: yes
  roles:
    - { role: firewall-ufw, tags: ['always'] }
    - { role: fail2ban, tags: ['always'] }
    - { role: fail2ban-ssh, tags: ['always'] }

- hosts: tomcat:apache
  vars_files:
    - "password/password-{{env}}.yml"
  become: yes
  roles:
    - { role: build-essential, tags: ['always'] }

- hosts: tomcat
  vars_files:
   - "password/password-{{env}}.yml"
  become: yes
  roles:
    - { role: jdk, tags: ['jdk'] }

- hosts: dbserver
  vars_files:
   - "password/password-{{env}}.yml"
  become: yes
  roles:
    - { role: postgres, tags: ['postgres'] }
    - { role: postgres_conf, tags: ['postgres_conf'] }
    - { role: postgres_instance, tags: ['postgres_instance'] }
    - { role: postgres_backup, tags: ['postgres_backup'] }
    #- { role: dbmaintain, tags: ['dbmaintain'] } # TODO Dbmaintain

- hosts: tomcat
  vars_files:
   - "password/password-{{env}}.yml"
  become: yes
  roles:
    - { role: tomcat, tags: ['tomcat'] }
    - { role: tomcat_conf, tags: ['tomcat_conf'] }
    - { role: tomcat_owasp, tags: ['tomcat_owasp'] }
    #- { role: tomcat_apps, tags: ['tomcat_apps'] }
    #- { role: tomcat_openssl, tags: ['tomcat_openssl'] }
    #- { role: tomcat_keytool, tags: ['tomcat_keytool'] }

- hosts: apache
  vars_files:
   - "password/password-{{env}}.yml"
  become: yes
  roles:
    - { role: apache, tags: ['apache'] }
    - { role: apache_conf, tags: ['apache_conf'] }
    - { role: apache_mod_security, tags: ['apache_mod_security'] }
    - { role: apache_status, tags: ['apache_status'] }
    - { role: apache_mod_jk, tags: ['apache_mod_jk'] }
    - { role: apache_private_ca, tags: ['apache_private_ca'] }
    - { role: apache_vhosts_mod_jk, tags: ['apache_vhosts_mod_jk'] }
    #- { role: apache_vhosts_mod_proxy, tags: ['apache_vhosts_mod_proxy'] }

- hosts: proftp
  vars_files:
   - "password/password-{{env}}.yml"
  become: yes
  roles:
    - { role: proftp, tags: ['proftp'] }
    - { role: proftp_conf, tags: ['proftp_conf'] }
    - { role: proftp_ssl, tags: ['proftp_ssl'] }
    - { role: fail2ban_proftpd, tags: ['fail2ban_proftpd'] }