---

###################
# Security
###################
#- hosts: all
  #vars_files:
   #- "password/password-{{env}}.yml"
  #become: yes
  #roles:
    #- { role: firewall, tags: ['firewall'] }
    #- { role: fail2ban, tags: ['fail2ban'] }
    #- { role: fail2ban_ssh, tags: ['fail2ban_ssh'] }
    #- { role: portsentry, tags: ['portsentry'] }

###################
# Monitoring
###################
#- hosts: all
  #vars_files:
   #- "password/password-{{env}}.yml"
  #become: yes
  #roles:
    #- { role: monit, tags: ['monit'] }
    #- { role: monit_sshd, tags: ['monit_sshd'] }

###################
# Time
###################
#- name: Set local timezone
  #copy: 
    #content: {{ timezone }}
    #dest: "/etc/timezone"
    #notify: update tzdata

#- hosts: all
  #vars_files:
   #- "password/password-{{env}}.yml"
  #become: yes
  #roles:
    #- { role: ntp, tags: ['ntp'] }

####################
# Install build essential
###################
#- hosts: all
  #vars_files:
   #- "password/password-{{env}}.yml"
  #become: yes
  #roles:
    #- { role: build_essential, tags: ['build_essential'] }


###################
# Install Data Base
###################
#- hosts: dbserver
  #vars_files:
   #- "password/password-{{env}}.yml"
  #become: yes
  #roles:
    #- { role: postgres, tags: ['postgres'] }
    #- { role: postgres_instance, tags: ['postgres_instance'] }
    #- { role: postgres_backup, tags: ['postgres_backup'] }
    ##- { role: dbmaintain, tags: ['dbmaintain'] } # TODO Dbmaintain or Liquibase ( à choisir en fonction de la techno de versionning de BDD utilisée en environnement de Dev)
    #- { role: monit_postgresql, tags: ['monit_postgresql'] }

###################
# Install Tomcat
###################
#- hosts: tomcat
  #vars_files:
   #- "password/password-{{env}}.yml"
  #become: yes
  #roles:
    #- { role: jdk, tags: ['jdk'] }
    #- { role: tomcat, tags: ['tomcat'] }
    #- { role: tomcat_conf, tags: ['tomcat_conf'] }
    #- { role: tomcat_owasp, tags: ['tomcat_owasp'] }
    ##- { role: tomcat_apps, tags: ['tomcat_apps'] }
    ##- { role: tomcat_openssl, tags: ['tomcat_openssl'] }
    ##- { role: tomcat_keytool, tags: ['tomcat_keytool'] }
    #- { role: monit_tomcat, tags: ['monit_tomcat'] }


###################
# Install Apache
###################
- hosts: apache
  vars_files:
   - "password/password-{{env}}.yml"
  become: yes
  roles:
    - { role: apache, tags: ['apache'] }
    - { role: apache_conf, tags: ['apache_conf'] }
    #- { role: apache_mod_security, tags: ['apache_mod_security'] }
    #- { role: apache_status, tags: ['apache_status'] }
    ##- { role: apache_mod_jk, tags: ['apache_mod_jk'] }
    ##- { role: apache_private_ca, tags: ['apache_private_ca'] }
    ###- { role: apache_vhosts_mod_jk, tags: ['apache_vhosts_mod_jk'] }
    ###- { role: apache_vhosts_mod_proxy, tags: ['apache_vhosts_mod_proxy'] }
    #- { role: monit_apache, tags: ['monit_apache'] }



##################
#Install ProFTP
##################
#- hosts: proftp
  #vars_files:
   #- "password/password-{{env}}.yml"
  #become: yes
  #roles:
    #- { role: proftp, tags: ['proftp'] }
    #- { role: proftp_fail2ban, tags: ['proftp_fail2ban'] }
    #- { role: proftp_ssl, tags: ['proftp_ssl'] }
    #- { role: monit_proftp, tags: ['monit_proftp'] }


#===========  Tâche à faire sur Ansible =====================
 ##TODO Roles
  #- apache_fail2ban
  #- Postfix
  #- HAProxy