---
- hosts: all
  vars_files:
    - "password/password-{{env}}.yml"
  become: yes
  roles:
    - { role: fail2ban, tags: ['always'] }
    - { role: fail2ban_ssh, tags: ['always'] }

- hosts: tomcat:apache
  vars_files:
    - "password/password-{{env}}.yml"
  become: yes
  roles:
    - { role: build_essential, tags: ['always'] }

- hosts: tomcat
  vars_files:
   - "password/password-{{env}}.yml"
  become: yes
  roles:
    - { role: jdk, tags: ['jdk'] }

- hosts: dbserver
  vars_files:
   - "password/password-{{env}}.yml"
  become: yes
  roles:
    - { role: postgres, tags: ['postgres'] }
    - { role: postgres_conf, tags: ['postgres_conf'] }
    - { role: postgres_instance, tags: ['postgres_instance'] }
    - { role: postgres_backup, tags: ['postgres_backup'] }
    #- { role: dbmaintain, tags: ['dbmaintain'] } # TODO Dbmaintain
    - { role: postgres_monitoring, tags: ['postgres_monitoring'] }

- hosts: tomcat
  vars_files:
   - "password/password-{{env}}.yml"
  become: yes
  roles:
    #- { role: tomcat, tags: ['tomcat'] }
    #- { role: tomcat_conf, tags: ['tomcat_conf'] }
    #- { role: tomcat_owasp, tags: ['tomcat_owasp'] }
    #- { role: tomcat_apps, tags: ['tomcat_apps'] }
    #- { role: tomcat_openssl, tags: ['tomcat_openssl'] }
    #- { role: tomcat_keytool, tags: ['tomcat_keytool'] }
    - { role: tomcat_monitoring, tags: ['tomcat_monitoring'] }

- hosts: apache
  vars_files:
   - "password/password-{{env}}.yml"
  become: yes
  roles:
    #- { role: apache, tags: ['apache'] }
    #- { role: apache_conf, tags: ['apache_conf'] }
    #- { role: apache_mod_security, tags: ['apache_mod_security'] }
    #- { role: apache_status, tags: ['apache_status'] }
    #- { role: apache_mod_jk, tags: ['apache_mod_jk'] }
    #- { role: apache_private_ca, tags: ['apache_private_ca'] }
    #- { role: apache_vhosts_mod_jk, tags: ['apache_vhosts_mod_jk'] }
    #- { role: apache_vhosts_mod_proxy, tags: ['apache_vhosts_mod_proxy'] }
    - { role: apache_monitoring, tags: ['apache_monitoring'] }

- hosts: proftp
  vars_files:
   - "password/password-{{env}}.yml"
  become: yes
  roles:
    - { role: proftp, tags: ['proftp'] }
    - { role: proftp_conf, tags: ['proftp_conf'] }
    - { role: proftp_ssl, tags: ['proftp_ssl'] }
    - { role: proftp_fail2ban, tags: ['proftp_fail2ban'] }
    - { role: proftp_monitoring, tags: ['proftp_monitoring'] }
    
#===========  Tâche à faire sur Ansible =====================
#II°) 
#Se pencher sur ce lien. 
#http://www.alphadevx.com/a/390-Installing-Ansible-on-Linux
#Penser à bien réécrire la procédure d'installation d'Ansible avec une typologie claire des machines. S'inspirer de http://denisrosenkranz.com/tutoha-introduction-a-haproxy-sous-debian-7/

#III°)
#1°)
    #Etablir un rôle firewall avec UFW et autoriser les ports
#S'inspirer de :
 #- https://github.com/weareinteractive/ansible-ufw
 #- http://blog.octo.com/securiser-son-serveur-avec-ansible/
 #- http://ryaneschinger.com/blog/securing-a-server-with-ansible/
    
#2°) Autoriser les autres ports des autres rôles avec UFW au fur et à mesur qu'on installe les autres programmes
#3°) Etablir un rôles pour installer Fail2ban
#IV°) Firewall manuel

#http://guide.ovh.com/firewall

#roles/commands_utils/
#roles/firewall_manual/
#roles/firewall_ufw/
#roles/portsentry_conf/