---
# tasks file for fail2ban-ssh
- name: Copy Jail Configuration file
  template:
    src: jail.conf.j2
    dest: "{{ fail2ban_conf_file }}"
    force: yes
    owner: root
    group: root
    
# TODO : Define mode for file jail.conf

- name: Restart Fail2ban
  command: echo "Restart Fail2ban..."
  notify:
    - Restart Fail2ban
