---
# tasks file for monit_sshd

- name: Copy configuration file
  template:
    backup: yes
    src: sshd.conf.j2
    dest: "{{ monit_sshd_config_file }}"
    owner: root
    group: root
    mode: 0644

- name: Reload monit
  command: echo "Reload monit..."
  notify:
    - Reload monit