---
# defaults file for sonarqube

gradle_version: "3.0"
gradle_archive_name: "gradle-{{ gradle_version }}-all.zip"
gradle_download_archive_url: ""
gradle_install_directory: "/opt/gradle"
gradle_home: "{{ gradle_install_dir }}/gradle-{{ gradle_version }}"

sonarqube_version: "6.3.1" 
sonarqube_archive_name: "sonarqube-{{ sonarqube_version }}.zip"
sonarqube_install_directory: "/opt/sonar"
sonarqube_home: "{{ sonarqube_install_directory }}/sonarqube-{{ sonarqube_version }}"
sonarqube_download_archive_url: ""
sonarqube_jdbc_username: 
sonarqube_jdbc_password: 
sonarqube_jdbc_url:
sonarqube_web_port: 9000