---
# tasks file for fail2ban_ssh

- name: Insert/Update the block into the jail Configuration file
  blockinfile:
    dest: "{{ fail2ban_jail_configuration_file }}"
    backup: yes
    insertafter: EOF
    block: |
        [ssh]
        enabled = {{ fail2ban_enabled }}
        port = ssh
        filter = sshd
        logpath = /var/log/auth.log
        maxretry = {{ sshd_maxretry }}
        bantime = {{ sshd_bantime }}
    marker: '#'
    owner: root
    group: root
    mode: 0644

- name: Restart Fail2ban
  command: echo "Restart Fail2ban..."
  notify:
    - Restart Fail2ban
