---
# defaults file for apache

apache_version: 2.4.23
apache_versions: /opt/apache_versions
apache_home: /opt/apache2
apache_last_version: "{{ apache_versions }}/httpd-{{ apache_version }}"
apache_tarball_name: "httpd-{{ apache_version }}.tar.gz"
apache_url: "{{ nexus_public_repository }}/org/apache/httpd/{{ apache_version }}/{{ apache_tarball_name }}"
apache_goss_enabled: False
apache_required_packages:
 - 'perl'
 - 'libpcre3'
 - 'libpcre3-dev'
 - 'zlib1g'
 - 'zlib1g-dev'
 - 'libxml2'
 - 'libxml2-dev'
 - 'libaprutil1'
 - 'libaprutil1-dev'
 - 'libssl-dev'
 - 'automake'
 - 'libapr1'
 - 'libapr1-dev'