---

- name: Stop eventual tomcat server running
  service:
    name: tomcat
    state: stopped
    enabled: no
  ignore_errors: true

- name : Remove eventual tomcat init script from the system
  file:
    path: "{{ tomcat_init_script }}"
    state: absent
  ignore_errors: true

- name: Create Group Tomcat
  group:
    name: "{{ tomcat_user_group }}"
    state: present

- name: Create User Tomcat
  user:
    name: "{{ tomcat_user }}"
    createhome: no
    group: "{{ tomcat_user_group }}"
    shell: /bin/bash
    state: present

- name: Change the owner of tomcat versions directory
  file:
    path: "{{ tomcat_versions }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user_group }}"
    recurse: yes

- name: Change the owner of link to the last tomcat directory
  file:
    src: "{{ tomcat_last_version }}"
    path: "{{ tomcat_home }}"
    state: link
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user_group }}"

- name: Create the tomcat configuration directory
  file:
    path: "{{ tomcat_conf_directory }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user_group }}"
    state: directory
    recurse: yes

- name: Deploy configuration Tomcat files
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    force: "{{item.force}}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user_group }}"
  with_items:
   - "{{ tomcat_conf_files }}"

- name: Copy Tomcat init script
  template:
    src: "tomcat.sh.j2"
    dest: "{{ tomcat_init_script }}"
    owner: root
    group: root
    force: yes
    mode: 0755

- name: Add Iptables Input trafic rule for Tomcat
  command: >
   /sbin/iptables -t filter -A INPUT -i {{ network_interface }} -p tcp --dport {{ tomcat_http_port }} -j ACCEPT -m comment --comment "TCP - Tomcat Server Input trafic"
  when: use_iptables_firewall

- name: Add Iptables Output trafic rule for Tomcat
  command: >
   /sbin/iptables -t filter -A OUTPUT -o {{ network_interface }} -p tcp --dport {{ tomcat_http_port }} -j ACCEPT -m comment --comment "TCP - Tomcat Server Output trafic"
  when: use_iptables_firewall

- name: Enable Tomcat service
  service:
    name: tomcat
    enabled: yes

- name: Restart tomcat
  command: echo "Restart Tomcat service..."
  notify:
    - Restart tomcat