---
# tasks file for fail2ban-proftpd
- name: Insert/Update the block into the jail Configuration file
  blockinfile:
    dest: "{{ fail2ban_jail_configuration_file }}"
    backup: yes
    insertafter: EOF
    block: |
        [proftpd]
        enabled = {{ fail2ban_enabled }}
        port = ftp,ftp-data,ftps,ftps-data
        filter = proftpd
        logpath = /var/log/proftpd/proftpd.log
        maxretry = {{ proftpd_maxretry }}
        bantime = {{ proftpd_bantime }}
    state: present
    marker: '#'
    owner: root
    group: root
    mode: 0644

- name: Restart Fail2ban
  command: echo "Restart Fail2ban..."
  notify:
    - Restart Fail2ban