---
# This playbook contains Apache installation.

- name: Stop eventual Apache server runing
  service: name=apache state=stopped enabled=no
  ignore_errors: true

- name: Install required librairies
  apt: pkg={{ item.package }} state=present
  with_items: "{{ apache_required_packages }}"
  
- name : Check apache versions directory exists
  stat: path={{ apache_versions }}
  register: apache_versions_dir_exists

- name: Create apache versions directory
  file: 
    path: "{{ apache_versions }}"
    state: directory
  when: not apache_versions_dir_exists.stat.exists
  
- name: Delete Apache home directory 
  file: 
    path: "{{ apache_home }}"
    state: absent

- name: Create Apache home directory
  file: 
    path: "{{ apache_home }}"
    state: directory
  
# TODO : Penser à ecrire un module pour interagir avec Nexus (https://github.com/mihxil/ansible-nexus/blob/master/nexus)
- name: Download Apache Archive
  get_url: 
    url: "{{ apache_url }}"
    url_username: "{{ nexus_user }}"
    url_password: "{{ nexus_user_password }}"
    dest: "/tmp/{{ apache_tarball_name }}"
    
- name: Decompress Apache archive
  unarchive: 
    src: "/tmp/{{ apache_tarball_name }}"
    dest: "{{ apache_versions }}/"

- name: Delete Apache archive
  file: 
    path: "/tmp/{{ apache_tarball_name }}"
    state: absent
    
- name: Compile Apache 
  shell: cd {{ apache_last_version }} &&
                ./configure 
                --prefix={{ apache_home }}
                --with-mpm=worker
                --enable-so
                --enable-cache
                --enable-cache_disk
                --enable-socache_memcache
                --enable-mod_dir
                --enable-imagemap
                --enable-include
                --enable-log_config
                --enable-logio
                --enable-log_debug
                --enable-proxy
                --enable-access
                --enable-mime
                --enable-rewrite
                --enable-alias
                --enable-deflate
                --enable-expires
                --enable-headers
                --enable-status
                --enable-ssl
                --enable-socache_shmcb
                --enable-setenvif
                --enable-socache_dbm               
                --disable-actions
                --disable-env
                --disable-authz_dbm
                --disable-cgi
                --disable-auth_digest
                --disable-authnz_ldap
                --disable-autoindex
                --disable-asis
                --disable-cgid
                --disable-negotiation
                --disable-userdir
                --disable-charset-lite
      
- name: Execute commands to install Apache. 
  shell: cd {{ apache_last_version }} && make && umask 022 && make install && make clean