---
# This playbook contains Mod JK installation

# Create Module Security directory
- name: Create Mod JK directory
  file: 
    path: "{{ mod_jk_unzip_dir }}"
    state: directory
  
# Unzip Mod JK archive
- name: Unzip Mod JK archive
  unarchive: 
    src: "{{ mod_jk_tarball_name }}"
    dest: "{{ mod_jk_unzip_dir }}/"

# Configure Mod JK
- name: Configure Mod JK
  shell: cd {{ mod_jk_dir }} && ./configure --with-apr={{ apr_config_file }} --with-apxs={{ apache_home }}/bin/apxs 
  
# Make & Make install Mod JK
- name: Make & Make install Mod JK
  shell: cd {{ mod_jk_dir }} && make && make install 

# Copy Mod JK library
- name: Copy Mod JK library
  shell: cp {{ mod_jk_dir }}/apache-2.0/mod_jk.so {{ apache_home }}/modules/
  
# Delete Mod JK install directory
- name: Delete Mod JK install directory
  file: 
    path: "{{ mod_jk_unzip_dir }}"
    state: absent