---
# This playbook contains Mod Security installation.

# Create Mod Security directory
- name: Create Mod Security directory
  file: 
    path: "{{ mod_security_unzip_dir }}"
    state: directory
  
# Unzip Mod Security archive
- name: Unzip Mod Security archive
  unarchive: 
    src: "{{ mod_security_tarball_name }}"
    dest: "{{ mod_security_unzip_dir }}/"
  
# Autogenerate Mod Security
- name: Autogenerate Mod Security
  shell: cd {{ mod_security_dir }} && ./autogen.sh 
 
# Configure Mod Security
- name: Configure Mod Security
  shell: cd {{ mod_security_dir }} && CFLAGS=-I/usr/include/libxml2 && ./configure --with-apxs={{ apache_home }}/bin/apxs 
  
# Make & Make install Mod Security
- name: Make & Make install Mod Security
  shell: cd {{ mod_security_dir }} && make && make install 
  
# Delete Mod Security install directory
- name: Delete Mod Security install directory
  file: 
    path: "{{ mod_security_unzip_dir }}"
    state: absent 
  
# Create log directory for Mod Security
- name: Create the log directory for Mod Security
  file: 
    path: "{{ mod_security_logs_dir }}"
    state: directory
    
# Create the configuration directory for Mod Security
- name: Create the configuration directory for Mod Security
  file: 
    path: "{{ mod_security_conf_dir }}"
    state: directory    
  
# Copy Mod Security library into Apache module directories
- name: Copy Mod Security library into Apache module directories
  shell: cp /usr/local/modsecurity/lib/mod_security2.so {{ apache_home }}/modules/

# Deploy Mod Security configuration files
- name: Deploy Mod Security configuration files
  template: 
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    force: "{{item.force}}"
  with_items: "{{ mod_security_conf_files }}"