---
# This playbook contains Mod SSL installation.

# Create Mod SSL Certificats authority directory
- name: Create Mod SSL Certificats authority directory
  file: 
    path: "{{ apache_ssl_ca_conf_dir }}"
    state: directory
    
# Create Module SSL new certificats directory
- name: Create Mod SSL new certificats directory
  file: 
    path: "{{ apache_ssl_ca_conf_dir }}/newcerts"
    state: directory

# Copy configuration file into CA directory
- name: Copy configuration file into CA directory
  template: 
    src: openssl_ca.conf.j2
    dest: "{{ apache_ssl_ca_conf_dir }}/openssl_ca.conf"
    force: yes
    
# Initialize serial & index.txt files
- name: Initialize serial & index.txt files
  shell: echo '01' > "{{ apache_ssl_ca_conf_dir }}/serial"  && touch "{{ apache_ssl_ca_conf_dir }}/index.txt"
  
  
# Create private Key of Certification Authority
- name: Create private Key of Certification Authority
  shell: openssl genrsa -out {{ apache_ssl_ca_key }} {{ apache_ssl_ca_bits }} -rand file:/dev/random

# Protect private Key of Certification Authority (Only read access for root who is the owner)
- name: Protect private Key of Certification Authority (Only read access for root who is the owner)
  file: 
    path: "{{ apache_ssl_ca_key }}"
    mode: 0400 
  
# Create X509 Certification for authority
- name: Create X509 Certification for authority
  shell: openssl req -new -x509 -key {{ apache_ssl_ca_key }} -out {{ apache_ssl_ca_cert }} -config "{{ apache_ssl_ca_conf_dir }}/openssl_ca.conf" -subj "{{ apache_ssl_ca_subj }}"