---
# tasks file for gradle

- name: Create gradle install directory
  file:
    path: "{{ gradle_install_directory }}"
    state: directory
    owner: root
    group: root

- name: Download, decompress and delete gradle archive
  unarchive:
    src: "{{ gradle_download_archive_url }}"
    dest: "{{ gradle_install_directory }}/"
    remote_src: True
  when: ansible_version.major|int >= 2
  
- name: Download gradle archive
  get_url:
    url: "{{ gradle_download_archive_url }}"
    dest: "/tmp/{{ gradle_archive_name }}"
  when: ansible_version.major|int < 2

- name: Decompress Apache archive
  unarchive:
    src: "/tmp/{{ gradle_archive_name }}"
    dest: "{{ gradle_dir }}/"
  when: ansible_version.major|int < 2

- name: Delete Apache archive
  file:
    path: "/tmp/{{ gradle_archive_name }}"
    state: absent
  when: ansible_version.major|int < 2

- name: Add/Update environments variables
  blockinfile:
    dest: "/etc/profile"
    insertafter: EOF
    block: |
      # Gradle Home
      GRADLE_HOME="{{ gradle_home }}"
      export GRADLE_HOME
      # Update PATH
      PATH=$PATH:"$GRADLE_HOME/bin"
      export PATH
    state: present

- name: Relaod environments variables
  command: >
    source /etc/profile
