---

  
# Generating keystore and certifcate...
- name: Generating keystore and certifcate...
  shell: keytool -genkey -noprompt -trustcacerts -keyalg RSA -alias {{ keystore_alias }} -dname "{{ keystore_subj }}" -keypass {{ keystore_password }} -keystore {{ keystore_file }} -storepass {{ keystore_password }} -validity {{ ssl_certificate_days }}




#subjectAltName="DNS:localhost" 


#subj="CN=localhost, OU=IT, O=Syscom, L=Lyon, S=Rhône, C=FR"


#keytool -genkey -alias keyAlias -keyalg RSA -keypass changeit -storepass changeit -keystore keystore.jks -noprompt -dname "${subj}"

# Make a request for certificat
#keytool -certreq -keyalg RSA -alias keyAlias -file certificate.csr -keystore keystore.jks

#  Creating a Self-Signed Certificate in a JKS Keystore by Using an RSA Key Algorithm
