---

- name: Installing python-psycopg2 package...
  apt:
    pkg: python-psycopg2
    state: present
  when: ansible_os_family == 'Debian'

- name: Installing python-psycopg2 package...
  yum:
    pkg: python-psycopg2
    state: present
  when: ansible_os_family == 'RedHat'

- name: Create user
  postgres_user:
    user: "{{ item.db_user }}"
    password: "{{ item.db_password }}"
    roles: "{{ item.db_user_roles }}"
    state: present
  with_items: "{{ dbs }}"

- name: Create database
  postgres_db:
    name: "{{ item.db_name }}"
    owner: "{{ item.db_user }}"
    state: present
  with_items: "{{ dbs }}"

- name: Create schema
  postgres_schema:
    database: "{{ item.db_name }}"
    schema: "{{ item.db_schema }}"
    user: "{{ item.db_user }}"
    state: present
  with_items: "{{ dbs }}"

- name: Restart PostgreSQL
  command: echo "Restart PostgreSQL"
  notify:
    - Restart PostgreSQL