postgres_port: 5432
postgres_version: 9.4
postgres_server_pkg: "postgresql-{{ postgres_version }}"
postgres_client_pkg: "postgresql-client-{{ postgres_version }}"
postgres_conf_dir: "/etc/postgresql/{{ postgres_version}}/main"
postgres_listen_addresses: '*'
firewall_specific_env_ports:
 - { port: '{{ postgres_port }}', protocol: 'tcp', direction: 'INPUT', comment: 'Postgres Input trafic' }
 - { port: '{{ postgres_port }}', protocol: 'tcp', direction: 'OUTPUT', comment: 'Postgres Output trafic' }
postgres_conf_files:
 - { src: 'postgresql.conf.j2', dest: '{{ postgres_conf_dir }}/postgresql.conf', force: yes }
 - { src: 'pg_hba.conf.j2', dest: '{{ postgres_conf_dir }}/pg_hba.conf', force: yes }
 