---
# tasks file for proftp_ssl

- name: Installing openssl...
  apt:
    pkg: openssl
    state: present

- name: Create ProFTP SSL configuration directory.
  file:
    path: "{{ proftp_ssl_conf_dir }}"
    state: directory
    owner: "{{ proftp_user }}"
    group: "{{ proftp_user_group }}"

- name: Deploy SSL Certification Authority (CA) configuration file
  template:
    src: openssl.conf.j2
    dest: "{{ proftp_ssl_config_file }}"
    force: yes

- name: Generate SSL files( Key & certificat).
  command: >
    openssl req -new
      -x509
      -nodes
      -days 3650
      -subj "{{ proftp_ssl_subj }}"
      -config {{ proftp_ssl_config_file }}
      -extensions v3_req
      -out {{ proftp_ssl_cert_file }}
      -keyout {{ proftp_ssl_key_file }}

- name: Secure private key file
  file:
    path: "{{ proftp_ssl_key_file }}"
    mode: 0400

- name: Deploy TLS configuration file
  template:
    src: tls.conf.j2
    dest: "{{ proftp_tls_conf_path }}"
    force: yes

- name: Include tls.conf in the proftp configuration
  lineinfile:
    dest: "{{ proftp_conf_path }}"
    regexp: ''
    insertafter: EOF
    line: 'Include "{{ proftp_tls_conf_path }}"'

- name: Define owner, group and right on ProFTP configuration files
  file:
    path: "{{ item.path }}"
    force: yes
    owner: "{{ proftp_user }}"
    group: "{{ proftp_user_group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ proftp_ssl_files }}"

- name: Restart ProFTP
  command: echo "Restart ProFTP service..."
  notify:
    - Restart ProFTP