---
# tasks file for tomcat_keytool


- name : Check tomcat keystore directory exists
  stat:
    path: "{{ keystore_dir }}"
  register: tomcat_keystore_directory_exists

- name: Create tomcat keystore directory
  file:
    path: "{{ keystore_dir }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user_group }}"
    state: directory
    recurse: yes
  when: not tomcat_keystore_directory_exists.stat.exists

- name: Generating keystore and certifcate...
  command: >
    keytool
      -genkey
      -noprompt
      -trustcacerts
      -keyalg RSA
      -alias {{ keystore_alias }}
      -dname "{{ keystore_subj }}"
      -keypass {{ vault_keystore_password }}
      -keystore {{ keystore_file }}
      -storepass {{ vault_keystore_password }}
      -validity 3650

- name: Deploy configuration files for Tomcat with openssl
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user_group }}"
  with_items:
   - "{{ keystore_conf_files }}"

- name: Restart tomcat
  command: echo "Restart Tomcat service..."
  notify:
    - Restart tomcat