---
use_iptables_firewall: False
postgres_listen_addresses: '*'
postgres_server_pkg: "postgresql-{{postgres_version}}"
postgres_client_pkg: "postgresql-client-{{postgres_version}}"
postgres_conf_files:
 - { src: 'postgresql.conf.j2', dest: '{{ postgres_conf_dir }}/postgresql.conf', force: yes }
 - { src: 'pg_hba.conf.j2', dest: '{{ postgres_conf_dir }}/pg_hba.conf', force: yes }