---
# This playbook contains apache virtual hosts installation.

# Create virtual hosts configuration directories
- name: Create virtual hosts configuration directories
  file: 
    path: "{{ apache_vhosts_conf_dir }}"
    state: directory
   
# Create logs directories for virtual hosts
- name: Create logs directories for virtual hosts
  file: 
    path: "{{ apache_logs_dir }}/{{ item.documentRoot }}"
    state: directory
  with_items: 
    - "{{ apache_vhosts_mod_jk }}"
    - "{{ apache_vhosts_mod_proxy }}"
    
# Create virtual hosts root directories
- name: Create virtual hosts root directories
  file: 
    path: "{{ apache_vhosts_dir }}/{{ item.documentRoot }}"
    state: directory
  with_items: 
    - "{{ apache_vhosts_mod_jk }}"
    - "{{ apache_vhosts_mod_proxy }}"

# Create virtual hosts mutex directories
- name: Create virtual mutex root directories
  file: 
    path: "{{ apache_vhosts_dir }}/{{ item.documentRoot }}/mutex"
    state: directory
  with_items: 
    - "{{ apache_vhosts_mod_jk }}"
    - "{{ apache_vhosts_mod_proxy }}"
   
# Mod Proxy configuration HTTP  - Generate virtual hosts configuration files
- name: Mod Proxy configuration HTTP  - Generate virtual hosts configuration files
  template: 
    src: vhosts_mod_proxy.conf.j2 
    dest: "{{ apache_vhosts_conf_dir }}/{{ item.documentRoot }}_mod_proxy.conf"
    force: yes
  with_items: 
    - "{{ apache_vhosts_mod_proxy }}"
  when: "{{ mod_proxy_enable }}"
  
  
# Copy workers.properties configuration file for Mod_Jk
- name: Copy workers.properties configuration file for Mod_Jk
  template: 
    src: workers_mod_jk.properties.j2 
    dest: "{{ apache_conf_dir }}/workers.properties"
    force: yes
  when: "{{ mod_jk_enable }}"
  
# Mod JK configuration - Generate virtual hosts configuration files
- name: Mod JK configuration - Generate virtual hosts configuration files
  template: 
    src: vhosts_mod_jk.conf.j2 
    dest: "{{ apache_vhosts_conf_dir }}/{{ item.documentRoot }}_mod_jk.conf"
    force: yes
  with_items: "{{ apache_vhosts_mod_jk }}"
  when: "{{ mod_jk_enable }}"
  
- name: Install SSL certificates for virtual hosts
  include: ssl_main.yml
  when: "{{ apache_with_ssl }}"
  
- name: Restart Apache
  command: echo "Restart Apache service..."
  notify: 
    - Restart Apache