---
# This playbook contains apache virtual hosts installation.

- name: Create virtual hosts configuration directories
  file: 
    path: "{{ apache_vhosts_conf_dir }}"
    state: directory
   
- name: Create logs directories for Mod_Jk virtual hosts
  file: 
    path: "{{ apache_logs_dir }}/{{ item.key }}"
    state: directory
  with_dict: "{{ apache_vhosts_mod_jk }}"

- name: Create logs directories for Mod_Proxy virtual hosts
  file: 
    path: "{{ apache_logs_dir }}/{{ item.key }}"
    state: directory
  with_dict: "{{ apache_vhosts_mod_proxy }}"
    
- name: Create virtual hosts root directories
  file: 
    path: "{{ apache_vhosts_dir }}/{{ item.key }}"
    state: directory
  with_dict: "{{ apache_vhosts_mod_jk }}"
  
- name: Create virtual hosts root directories
  file: 
    path: "{{ apache_vhosts_dir }}/{{ item.key }}"
    state: directory
  with_dict: "{{ apache_vhosts_mod_proxy }}"
  
- name: Create virtual mutex directories
  file: 
    path: "{{ apache_vhosts_dir }}/{{ item.key }}/mutex"
    state: directory
  with_dict: "{{ apache_vhosts_mod_jk }}"
    
- name: Create virtual mutex directories
  file: 
    path: "{{ apache_vhosts_dir }}/{{ item.key }}/mutex"
    state: directory
  with_dict: "{{ apache_vhosts_mod_proxy }}"
   
- name: Mod Proxy configuration HTTP  - Generate virtual hosts configuration files
  template: 
    src: vhosts_mod_proxy.conf.j2 
    dest: "{{ apache_vhosts_conf_dir }}/{{ item.key }}_mod_proxy.conf"
    force: yes
  with_dict: "{{ apache_vhosts_mod_proxy }}"
  when: "{{ mod_proxy_enable }}"
  
- name: Copy workers.properties configuration file for Mod_Jk
  template: 
    src: workers_mod_jk.properties.j2 
    dest: "{{ apache_conf_dir }}/workers.properties"
    force: yes
  when: "{{ mod_jk_enable }}"
  
- name: Mod JK configuration - Generate virtual hosts configuration files
  template: 
    src: vhosts_mod_jk.conf.j2 
    dest: "{{ apache_vhosts_conf_dir }}/{{ item.key }}_mod_jk.conf"
    force: yes
  with_dict: "{{ apache_vhosts_mod_jk }}"
  when: "{{ mod_jk_enable }}"
  
- name: Install SSL certificates for virtual hosts
  include: ssl_main.yml
  when: "{{ apache_enable_ssl }}"
  
- name: Restart Apache
  command: echo "Restart Apache service..."
  notify: 
    - Restart Apache