---
# This playbook installs SSL configuration files for apache virtual hosts.

# Create virtual hosts root directories
- name: Create virtual hosts ssl directories
  file: 
    path: "{{ apache_vhosts_dir }}/{{ item.documentRoot }}/ssl"
    state: directory
  with_items: 
    - "{{ apache_vhosts_mod_jk }}"
    - "{{ apache_vhosts_mod_proxy }}"
  when: "{{ item.use_https }}"

# Create passhprase
- name: Create passhprase
  shell: openssl rand -base64 48 > "{{ apache_vhosts_dir }}/{{ item.documentRoot }}/ssl/passphrase.txt"
  with_items: 
    - "{{ apache_vhosts_mod_jk }}"
    - "{{ apache_vhosts_mod_proxy }}"
  when: "{{ item.use_https }}"
 
# Secure passhprase
- name: Secure passhprase
  file: 
    path: "{{ apache_vhosts_dir }}/{{ item.documentRoot }}/ssl/passphrase.txt"
    mode: 0400
  with_items: 
    - "{{ apache_vhosts_mod_jk }}"
    - "{{ apache_vhosts_mod_proxy }}"
  when: "{{ item.use_https }}"
  
# Copy Script shell script which will read passphrase.txt
- name: Copy Script shell script which will read passphrase.txt
  template:
    src: passphrase.sh.j2 
    dest: "{{ apache_vhosts_dir }}/{{ item.documentRoot }}/ssl/passphrase.sh"
    force: yes
  with_items: 
    - "{{ apache_vhosts_mod_jk }}"
    - "{{ apache_vhosts_mod_proxy }}"
  when: "{{ item.use_https }}"
  
# Secure passphrase.sh
- name: Secure passphrase.sh
  file: 
    path: "{{ apache_vhosts_dir }}/{{ item.documentRoot }}/ssl/passphrase.sh"
    mode: 0500
  with_items: 
    - "{{ apache_vhosts_mod_jk }}"
    - "{{ apache_vhosts_mod_proxy }}"
  when: "{{ item.use_https }}"
  
# Create the private key for the virtual hosts
- name: Create the private key for the virtual hosts
  shell: cd "{{ apache_vhosts_dir }}/{{ item.documentRoot }}/ssl" && openssl genrsa -des3 -passout file:passphrase.txt -out key.pem {{ apache_ssl_ca_bits }} -rand file:/dev/random
  with_items: 
    - "{{ apache_vhosts_mod_jk }}"
    - "{{ apache_vhosts_mod_proxy }}"
  when: "{{ item.use_https }}"
  
# Secure private key file
- name: Secure private key file
  file: 
    path: "{{ apache_vhosts_dir }}/{{ item.documentRoot }}/ssl/key.pem"
    mode: 0400
  with_items: 
    - "{{ apache_vhosts_mod_jk }}"
    - "{{ apache_vhosts_mod_proxy }}"
  when: "{{ item.use_https }}"

# Create a certificat signing request for the virtual hosts
- name: Create a certificat signing request for the virtual hosts
  shell: cd "{{ apache_vhosts_dir }}/{{ item.documentRoot }}/ssl" && openssl req -new -passin file:passphrase.txt -key key.pem -out req.pem -subj "{{ apache_vhosts_ssl_subj }}" -config "{{ apache_ssl_ca_conf_dir }}/openssl_ca.conf"
  with_items: 
    - "{{ apache_vhosts_mod_jk }}"
    - "{{ apache_vhosts_mod_proxy }}"
  when: "{{ item.use_https }}"

# Sign the certificat for the virtual hosts
- name: Sign the certificat for the virtual hosts
  shell: cd "{{ apache_vhosts_dir }}/{{ item.documentRoot }}/ssl" && openssl ca -batch -notext -out cert.pem -config {{ apache_ssl_ca_conf_dir }}/openssl_ca.conf -infiles req.pem
  with_items: 
    - "{{ apache_vhosts_mod_jk }}"
    - "{{ apache_vhosts_mod_proxy }}"
  when: "{{ item.use_https }}"