---
# tasks file for maven

maven_version: "3.3.9"
maven_archive_name: "apache-maven-{{ maven_version }}-bin.tar.gz"
maven_install_directory: "/opt/maven"
maven_home: "{{ maven_install_directory }}/apache-maven-{{ maven_version }}"
maven_download_archive_url: ""

- name: Create maven directory
  file:
    path: "{{ maven_install_directory }}"
    state: directory
    owner: root
    group: root

- name: Download, decompress and delete maven archive
  unarchive:
    src: "{{ maven_download_archive_url }}"
    dest: "{{ maven_install_directory }}/"
    remote_src: True
  when: ansible_version.major|int >= 2
  
- name: Download maven archive
  get_url:
    url: "{{ maven_download_archive_url }}"
    dest: "/tmp/{{ maven_archive_name }}"
  when: ansible_version.major|int < 2

- name: Decompress maven archive
  unarchive:
    src: "/tmp/{{ maven_archive_name }}"
    dest: "{{ maven_dir }}/"
  when: ansible_version.major|int < 2

- name: Delete maven archive
  file:
    path: "/tmp/{{ maven_archive_name }}"
    state: absent
  when: ansible_version.major|int < 2

- name: Add/Update environments variables
  blockinfile:
    dest: "/etc/profile"
    insertafter: EOF
    block: |
      # Maven Home
      M2_HOME="{{ maven_dir }}/{{ maven_home }}"
      export M2_HOME
      # Update PATH
      PATH=$PATH:"$M2_HOME/bin"
      export PATH
    state: present

- name: Relaod environments variables
  command: >
    source /etc/profile
