---
# tasks file for maven

- name: Create maven directory
  file:
    path: "{{ maven_install_directory }}"
    state: directory
    owner: root
    group: root

- name: Download, decompress and delete maven archive
  unarchive:
    src: "{{ maven_download_archive_url }}"
    dest: "{{ maven_install_directory }}/"
    remote_src: True
  when: ansible_version.major|int >= 2
  
- name: Download maven archive
  get_url:
    url: "{{ maven_download_archive_url }}"
    dest: "/tmp/{{ maven_archive_name }}"
  when: ansible_version.major|int < 2

- name: Decompress maven archive
  unarchive:
    src: "/tmp/{{ maven_archive_name }}"
    dest: "{{ maven_install_directory }}/"
  when: ansible_version.major|int < 2

- name: Delete maven archive
  file:
    path: "/tmp/{{ maven_archive_name }}"
    state: absent
  when: ansible_version.major|int < 2

- name: Add/Update environments variables
  blockinfile:
    dest: "/etc/profile"
    insertafter: EOF
    block: |
      # Maven Home
      M2_HOME="{{ maven_home }}"
      export M2_HOME
      # Update PATH
      PATH=$PATH:"$M2_HOME/bin"
      export PATH
    state: present

- name: Relaod environments variables
  shell: . /etc/profile

