---

- name: Check if tomcat is installed on the system
  shell: cat "{{ tomcat_home }}/RELEASE-NOTES"|grep "Apache Tomcat Version" || echo "Unknown Tomcat Server"
  register: tomcat_version_result

- include: install.yml
  when: "'{{ tomcat_version }}' not in '{{ tomcat_version_result.stdout }}'"