---
# This playbook deploys the whole application.  

#  Apply common & firewall roles to all nodes
#- hosts: dbserver:tomcat:apache
- hosts: tomcat:apache
  become: yes
  roles:
    - { role: common, tags: ['always'] }
    - { role: firewall, tags: ['always'] }
    
# Install JDK
- hosts: tomcat
  become: yes
  pre_tasks:
   - name: Get JDK/Java version installed on the nodes
     shell: java -version 2>&1 | head -n 1 | cut -d'"' -f2
     register: java_installed_version
  roles:
    - { role: jdk, when: " '{{ java_installed_version.stdout }}' != '{{ java_version }}'", tags: ['jdk'] }
    
#Install Postgres SGBD, schema and/or Dbmaintain
- hosts: dbserver
  become: yes
  roles:
    - { role: postgres, tags: ['postgres'] }
    - { role: postgres_instance, tags: ['postgres_instance'] }
    

# Install Tomcat
- hosts: tomcat
  become: yes
  roles:
    - { role: tomcat, tags:['tomcat'] }
    - { role: tomcat_apps, tags:['tomcat_apps'] } # TODO Install Tomcat Web application
    
    
# Install Apache Server
- hosts: apache
  become: yes
  roles:
    - { role: apache, tags:['apache'] }
    - { role: apache_vhosts, tags:['apache_vhosts'] }
    
    
#Install ProFTP
- hosts: proftp
  become: yes
  pre_tasks:
   - name: Check if ProFTP is installed on the system
     shell: proftpd --version || echo "unknown"
     register: proftpd_version
  roles:
    - { role: proftp, when: "'{{ proftpd_version.stdout }}'.find('unknown') != -1", tags:['proftp'] }