---
# This playbook deploys the whole application.  

#  Apply common & firewall roles to all nodes
#- hosts: dbserver:tomcat:apache
- hosts: tomcat:apache
  become: yes
  roles:
    - common
    - firewall
    
# Install java/jdk 
- hosts: tomcat
  become: yes
  pre_tasks:
   - name: Get java version installed on the nodes
     shell: java -version 2>&1 | head -n 1 | cut -d'"' -f2
     register: java_installed_version
  roles:
    - { role: jdk, when: " '{{ java_installed_version.stdout }}' != '{{ java_version }}'" }
    
#Install Postgres SGBD
- hosts: dbserver
  become: yes
  roles:
    - postgres 
    
# Install data base instance
- hosts: dbserver
  become: yes
  roles:
    - postgres_instance

# Install Tomcat
- hosts: tomcat
  become: yes
  roles:
    - tomcat
    
# Install Apache & Virtual hosts
- hosts: apache
  become: yes
  roles:
    - apache
    - apache_vhosts
    
#Install ProFTP
- hosts: proftp
  become: yes
  pre_tasks:
   - name: Check if ProFTP is installed on the system
     shell: proftpd --version || echo "unknown"
     register: proftpd_version
  roles:
    - { role: proftp, when: "'{{ proftpd_version.stdout }}'.find('unknown') != -1" }