---
# This playbook deploys the whole application.  

# 1 - Apply common roles to all nodes


# 2 - Apply jdk roles to all nodes
#- name: apply jdk installation to all nodes
- hosts: all
  su_user: root
  roles:
      - jdk     