---
# This playbook deploys the whole application.  

# 1 - Apply common & firewall roles to all nodes
#- hosts: dbserver|tomcat-middle|apache-front : TODO - Reactivate this config
- hosts: tomcat-middle:apache-front
  become: yes
  roles:
    - common
    - firewall
    
# 2  - Install java/jdk to all nodes 
- hosts: all
  become: yes
  pre_tasks:
   - name: Get java version installed on the nodes
     shell: java -version 2>&1 | head -n 1 | cut -d'"' -f2
     register: java_installed_version
  roles:
    - { role: jdk, when: " '{{ java_installed_version.stdout }}' != '{{ java_version }}'" }
    
# 3 - Install data base
- hosts: dbserver
  become: yes
  roles:
    - postgres_instance

# 4 - Install Tomcat
- hosts: tomcat-middle
  become: yes
  roles:
    - tomcat
    
# 5 - Install Apache frontal TODO