---
# This playbook deploys the whole application.  

# 1 - Apply common roles to all nodes


#- name: apply jdk installation to all nodes
#- hosts: all
  #become: yes
  #roles:
    #- jdk
    
# 2 - Apply Tomcat role to tomcat web server

- hosts: webserver
  become: yes
  roles:
    - tomcat