---
#apache_version: 2.4.18
apache_version: 2.4.23
apache_versions: /opt/apache_versions
apache_last_version: "{{ apache_versions }}/httpd-{{ apache_version }}"
apache_home: /opt/apache2
apache_vhosts_dir: "{{ apache_home }}/vhosts"
apache_tarball_name: "httpd-{{ apache_version }}.tar.gz"
apache_logs_dir: "{{ apache_home }}/logs"
apache_conf_dir: "{{ apache_home }}/conf"
apache_init_script: /etc/init.d/apache
apache_user: wwwd
apache_user_group: wwwd
apache_required_packages:
 - { package: 'perl' }
 - { package: 'libpcre3' }
 - { package: 'libpcre3-dev' }
 - { package: 'zlib1g' }
 - { package: 'zlib1g-dev' }
 - { package: 'libxml2' }
 - { package: 'libxml2-dev' } 
 - { package: 'libaprutil1' } 
 - { package: 'libaprutil1-dev' } 
 - { package: 'libssl-dev' }
 - { package: 'automake' } 
apache_server_dns: localhost
apache_server_admin: admin@example.com
apache_conf_files:
 - { src: 'httpd.conf.j2', dest: '{{ apache_conf_dir }}/httpd.conf', force: yes }
 
# Logs level possibilities : debug, info, notice, warn, error, crit, alert, emerg.
apache_conf_log_level: warn
apache_conf_max_clients: 300
apache_conf_keep_alive: 'On'
apache_conf_max_keep_alive_requests: 500 
apache_conf_keep_alive_timeout: 15

# SSL Certificate Authority TODO : à enlever
apache_enable_ssl: true

# Activation mod_jk TODO : à enlever
mod_jk_enable: true

# Configuration mod_proxy
mod_proxy_enable: true

apache_vhosts_conf_dir: "{{ apache_conf_dir }}/vhosts"

apache_vhosts_mod_jk:
  vhost1:
    serverName: 'vhosts1.fr'
    serverAlias: 'www.vhosts1.fr'
    use_https: true
    ssl_subj: "/C=\"{{ ssl_country }}\"/ST=\"{{ ssl_state }}\"/L=\"{{ ssl_locality }}\"/O=\"{{ ssl_organisation }}\"/OU=\"{{ ssl_organisation_unit }}\"/CN=vhosts1.fr"
    webapps: 'docs'
    workers:
        - { name: 'worker1', host: 'st-db-villeurbanne', port: '8009' }
        - { name: 'worker2', host: 'localhost', port: '8009' }
    
apache_vhosts_mod_proxy:
  vhosts2:
    serverName: 'vhosts2.fr'
    serverAlias: 'www.vhosts2.fr'
    use_https: false
    ssl_subj: ""
    webapps: 'examples'
    host: 'st-db-villeurbanne'
    port: '8080'