---
apache_version: 2.4.18
apache_versions: /opt/apache_versions
apache_last_version: "{{ apache_versions }}/httpd-{{ apache_version }}"
apache_home: /opt/apache2
apache_vhosts_dir: "{{ apache_home }}/vhosts"
apache_tarball_name: "httpd-{{ apache_version }}.tar.gz"
apache_logs_dir: "{{ apache_home }}/logs"
apache_conf_dir: "{{ apache_home }}/conf"
apache_init_script: /etc/init.d/apache
apache_user: wwwd
apache_user_group: wwwd
apache_required_packages:
 - { package: 'perl' }
 - { package: 'libpcre3' }
 - { package: 'libpcre3-dev' }
 - { package: 'zlib1g' }
 - { package: 'zlib1g-dev' }
 - { package: 'libxml2' }
 - { package: 'libxml2-dev' } 
 - { package: 'libaprutil1' } 
 - { package: 'libaprutil1-dev' } 
 - { package: 'libssl-dev' }
 - { package: 'automake' } 
mod_security_version: 2.9.1
mod_security_tarball_name: "modsecurity-{{ mod_security_version }}.tar.gz"
mod_security_unzip_dir: /opt/mod_security
mod_security_dir: "{{ mod_security_unzip_dir }}/modsecurity-{{ mod_security_version }}"
mod_security_logs_dir: "{{ apache_logs_dir }}/modsecurity"
mod_security_conf_dir: "{{ apache_conf_dir }}/modsecurity"
mod_security_conf_files:
 - { src: 'modsecurity.conf.j2', dest: '{{ mod_security_conf_dir }}/modsecurity.conf', force: yes }
 - { src: 'modsecurity_crs_10_setup.conf.j2', dest: '{{ mod_security_conf_dir }}/modsecurity_crs_10_setup.conf', force: yes }
 - { src: 'modsecurity_crs_16_session_hijacking.conf.j2', dest: '{{ mod_security_conf_dir }}/modsecurity_crs_16_session_hijacking.conf', force: yes }
 - { src: 'modsecurity_crs_41_sql_injection_attacks.conf.j2', dest: '{{ mod_security_conf_dir }}/modsecurity_crs_41_sql_injection_attacks.conf', force: yes }
 - { src: 'modsecurity_crs_43_csrf_protection.conf.j2', dest: '{{ mod_security_conf_dir }}/modsecurity_crs_43_csrf_protection.conf', force: yes }
 - { src: 'modsecurity_crs_41_xss_attacks.conf.j2', dest: '{{ mod_security_conf_dir }}/modsecurity_crs_41_xss_attacks.conf', force: yes }
 - { src: 'modsecurity_crs_49_inbound_blocking.conf.j2', dest: '{{ mod_security_conf_dir }}/modsecurity_crs_49_inbound_blocking.conf', force: yes }

apache_server_dns: localhost
apache_server_admin: admin@example.com
apache_conf_files:
 - { src: 'httpd.conf.j2', dest: '{{ apache_conf_dir }}/httpd.conf', force: yes }
 
# Logs level possibilities : debug, info, notice, warn, error, crit, alert, emerg.
apache_conf_log_level: warn
apache_conf_max_clients: 300
apache_conf_keep_alive: 'On'
apache_conf_max_keep_alive_requests: 500 
apache_conf_keep_alive_timeout: 15

# SSL Certificate Authority 
apache_with_ssl: true
apache_ssl_ca_bits: 2048
apache_ssl_ca_md: sha256
apache_ssl_ca_conf_dir: "{{ apache_conf_dir }}/ssl/ca"
apache_ssl_ca_key: "{{ apache_ssl_ca_conf_dir }}/ca_key.pem"
apache_ssl_ca_cert: "{{ apache_ssl_ca_conf_dir }}/ca_cert.pem"
apache_ssl_ca_default_days: "{{ ssl_certificate_days }}"
apache_ssl_ca_country: FR
apache_ssl_ca_state: Rhone
apache_ssl_ca_locality: Lyon
apache_ssl_ca_organisation: Syscom
apache_ssl_ca_organisation_unit: IT
apache_ssl_ca_name: Authority Company Inc,
apache_ssl_ca_subj: "/C=\"{{ apache_ssl_ca_country }}\"/ST=\"{{ apache_ssl_ca_state }}\"/L=\"{{ apache_ssl_ca_locality }}\"/O=\"{{ apache_ssl_ca_organisation }}\"/OU=\"{{ apache_ssl_ca_organisation_unit }}\"/CN={{ apache_ssl_ca_name }}"

# Configuration mod_jk
mod_jk_enable: true
mod_jk_version: 1.2.41
mod_jk_unzip_dir: /opt/mod_jk
mod_jk_dir: "{{ mod_jk_unzip_dir }}/tomcat-connectors-{{ mod_jk_version }}-src/native"
mod_jk_tarball_name: "tomcat-connectors-{{ mod_jk_version }}-src.tar.gz"

# Configuration mod_proxy
mod_proxy_enable: true

apache_vhosts_conf_dir: "{{ apache_conf_dir }}/vhosts"

apache_vhosts_mod_jk:
  vhost1:
    serverName: 'vhosts1.fr'
    serverAlias: 'www.vhosts1.fr'
    use_https: true
    webapps: 'docs'
    workers:
        - { name: 'worker1', host: 'st-db-villeurbanne', port: '8009' }
        - { name: 'worker2', host: 'localhost', port: '8009' }
    
apache_vhosts_mod_proxy:
  vhosts2:
    serverName: 'vhosts2.fr'
    serverAlias: 'www.vhosts2.fr'
    use_https: false
    webapps: 'examples'
    host: 'st-db-villeurbanne'
    port: '8080'
        
#apache_vhosts_mod_jk:
 #- { serverName: 'vhosts1.fr', serverAlias: 'www.vhosts1.fr', documentRoot: 'vhosts1', tomcat_host: 'st-db-villeurbanne', worker: 'worker1', webapps: 'docs', use_https: false }

#apache_vhosts_mod_proxy:
 #- { serverName: 'vhosts2.fr', serverAlias: 'www.vhosts2.fr', documentRoot: 'vhosts2', tomcat_host: 'st-db-villeurbanne', webapps: 'examples', use_https: false }


ssl_common_name: "vhosts1.fr"
apache_vhosts_ssl_subj: "/C=\"{{ ssl_country }}\"/ST=\"{{ ssl_state }}\"/L=\"{{ ssl_locality }}\"/O=\"{{ ssl_organisation }}\"/OU=\"{{ ssl_organisation_unit }}\"/CN={{ ssl_common_name }}"
