---
tomcat_version: 8.0.32
tomcat_versions: "/opt/tomcat_versions"
tomcat_home: /opt/tomcat
tomcat_user: tomcat
tomcat_user_group: tomcat
tomcat_last_version: "{{ tomcat_versions }}/apache-tomcat-{{ tomcat_version }}"
tomcat_tarball_name: "apache-tomcat-{{ tomcat_version }}.tar.gz"

tomcat_required_packages:
 - { package: 'libapr1' } 
 - { package: 'libapr1-dev' } 
 - { package: 'libaprutil1' } 
 - { package: 'libaprutil1-dev' } 
 - { package: 'libssl-dev' }

firewall_specific_env_ports:
 - { port: '{{ tomcat_http_port }}', protocol: 'tcp', direction: 'INPUT', comment: 'HTTP Tomcat Input trafic' }
 - { port: '{{ tomcat_http_port }}', protocol: 'tcp', direction: 'OUTPUT', comment: 'HTTP Tomcat Output trafic' }
 - { port: '{{ tomcat_https_port }}', protocol: 'tcp', direction: 'INPUT', comment: 'HTTPS Tomcat Input trafic' }
 - { port: '{{ tomcat_https_port }}', protocol: 'tcp', direction: 'OUTPUT', comment: 'HTTPS Tomcat Output trafic' }
 - { port: '{{ tomcat_mod_jk_port }}', protocol: 'tcp', direction: 'INPUT', comment: 'Tomcat Mod JK Input trafic' }
 - { port: '{{ tomcat_mod_jk_port }}', protocol: 'tcp', direction: 'OUTPUT', comment: 'Tomcat Mod JK Output trafic' }
 
libtcnative_version: 1.1.34
libtcnative_util_home: "{{ tomcat_last_version }}/bin/tomcat-native-{{ libtcnative_version }}-src/jni/native"
libtcnative_util_tarball_name: "tomcat-native-{{ libtcnative_version }}-src.tar.gz"
 
secure_conf_dir: "{{ tomcat_last_version }}/conf/ssl"
# SSL with Java Keystore
keystore_ssl_enable: false
keystore_file: "{{ keystore_conf_dir }}/keystore.jks"
keystore_conf_dir: "{{ secure_conf_dir }}"
keystore_password: secret
keystore_alias: keyAlias
keystore_subj: "CN={{ tomcat_dns }}, OU={{ ssl_organisation_unit }}, O={{ ssl_organisation }}, L={{ ssl_locality }}, S={{ ssl_state }}, C={{ ssl_country }}"


# SSL with Openssl configuration variables
ssl_cert_password: password
open_ssl_enable: false
open_ssl_conf_dir: "{{ secure_conf_dir }}"
open_ssl_certificate_file: "{{ open_ssl_conf_dir }}/cacert_{{ tomcat_dns }}.crt"
open_ssl_private_key_file: "{{ open_ssl_conf_dir }}/cacert_{{ tomcat_dns }}.key"
open_ssl_cert_config_file: "{{ tomcat_last_version }}/conf/openssl.conf"
open_ssl_cert_subjectAltName: "DNS:{{ tomcat_dns }}"
open_ssl_cert_password: secret
open_ssl_cert_common_name: "{{ tomcat_dns }}"
open_ssl_subj: "/C=\"{{ ssl_country }}\"/ST=\"{{ ssl_state }}\"/L=\"{{ ssl_locality }}\"/O=\"{{ ssl_organisation }}\"/OU=\"{{ ssl_organisation_unit }}\"/CN={{ open_ssl_cert_common_name }}"