---

- name: Installing fail2ban
  apt:
    pkg: fail2ban
    state: present
  when: ansible_os_family == 'Debian'

- name: Installing fail2ban
  yum:
    pkg: fail2ban
    state: present
  when: ansible_os_family == 'RedHat'

- name: Copy original fail2ban configuration
  copy:
    src: "{{ fail2ban_jail_configuration_file }}"
    dest: "{{ fail2ban_jail_configuration_orig_file }}"
    owner: root
    group: root
    force: yes
    mode: 0644

- name: Copy fail2ban configuration file jail.conf
  template:
    src: jail.conf.j2
    dest: "{{ fail2ban_jail_configuration_file }}"
    owner: root
    group: root
    force: yes
    mode: 0644

- name: Remove Required-Start line from fail2ban init script
  lineinfile:
    backup: yes
    dest: "{{ fail2ban_init_script }}"
    regexp: '^(.*)# Required-Start:(.*)'
    state: absent
  when: use_iptables_firewall

- name: Modify fail2ban init script to run after firewall script
  lineinfile:
    backup: yes
    dest: "{{ fail2ban_init_script }}"
    line: '# Required-Start:    $local_fs $remote_fs $firewall'
    insertafter: '^(.*)# Provides:(.*)'
  when: use_iptables_firewall

#https://www.how-to.ovh/viewtopic.php?t=19
#Au fur et à mesure qu'on ajoute d'autre programme, on ajoutera la config fail2ban correspondant : Apache, Postfix, Proftp