---

- name: Installing fail2ban
  apt:
    pkg: fail2ban
    state: present

- name : Check original fail2ban configuration file exists
  stat:
    path: "{{ fail2ban_jail_configuration_orig_file }}"
  register: fail2ban_conf_orig_file_exists
  when: iptables_enabled

- name: Copy original fail2ban configuration
  copy:
    src: "{{ fail2ban_jail_configuration_file }}"
    dest: "{{ fail2ban_jail_configuration_orig_file }}"
    owner: root
    group: root
    force: yes
    mode: 0644
  when: fail2ban_conf_orig_file_exists is defined and not fail2ban_conf_orig_file_exists.stat.exists

- name: Copy fail2ban configuration file jail.conf
  template:
    src: jail.conf.j2
    dest: "{{ fail2ban_jail_configuration_file }}"
    owner: root
    group: root
    force: yes
    mode: 0644

- name: Remove Required-Start line from fail2ban init script
  lineinfile:
    backup: yes
    dest: "{{ fail2ban_init_script }}"
    regexp: '^(.*)# Required-Start:(.*)'
    state: absent
  when: iptables_enabled

- name: Modify fail2ban init script to run after firewall script
  lineinfile:
    backup: yes
    dest: "{{ fail2ban_init_script }}"
    line: '# Required-Start:    $local_fs $remote_fs $firewall'
    insertafter: '^(.*)# Provides:(.*)'
  when: iptables_enabled