---

- name: Insert/Update the block into the jail Configuration file for proftp
  blockinfile:
    dest: "{{ fail2ban_jail_configuration_file }}"
    insertafter: EOF
    block: |
        [proftpd]
        enabled = true
        port = ftp,ftp-data,ftps,ftps-data
        filter = proftpd
        logpath = /var/log/proftpd/proftpd.log
        maxretry = {{ fail2ban_proftp_maxretry }}
        bantime = {{ fail2ban_proftp_bantime }}
    state: present
    marker: '#'
    owner: root
    group: root
    mode: 0644
  when: fail2ban_proftp_enabled