---
# This playbook contains iptables rules for ProFTP.

- name: Add Iptables Input trafic rule for ProFTP
  command: >
   /sbin/iptables -t filter -A INPUT -i {{ proftp_network_interface }} -p tcp --dport {{ proftp_default_port }} -j ACCEPT -m comment --comment "TCP - ProFTP Server Input trafic"

- name: Add Iptables Output trafic rule for ProFTP
  command: >
   /sbin/iptables -t filter -A OUTPUT -o {{ proftp_network_interface }} -p tcp --dport {{ proftp_default_port }} -j ACCEPT -m comment --comment "TCP - ProFTP Server Output trafic"

- name: Add Iptables Input trafic rule for ProFTP passive ports
  command: >
   /sbin/iptables -t filter -A INPUT -i {{ proftp_network_interface }} -p tcp --dport {{ proftp_firwall_ftp_min_passive_port }}:{{ proftp_firwall_ftp_max_passive_port }} -j ACCEPT -m comment --comment "TCP - ProFTP Server Input trafic - Passive ports"

- name: Add Iptables Output trafic rule for ProFTP passive ports
  command: >
   /sbin/iptables -t filter -A OUTPUT -o {{ proftp_network_interface }} -p tcp --dport {{ proftp_firwall_ftp_min_passive_port }}:{{ proftp_firwall_ftp_max_passive_port }} -j ACCEPT -m comment --comment "TCP - ProFTP Server Output trafic - Passive ports"