---
# This playbook contains ProFTP installation.

- name: Check if ProFTP is installed on the system
  shell: proftpd --version || echo "Unknown ProFTP Server"
  register: proftp_version_result

- name: Purge ProFTPd Server package if present
  apt:
    pkg: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - "proftpd"
    - "proftpd-basic"
  when: "('{{ proftp_version }}' not in '{{ proftp_version_result.stdout }}') and (ansible_os_family == 'Debian')"

- name: Purge ProFTPd Server package if present
  yum:
    pkg: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - "proftpd"
    - "proftpd-basic"
  when: "('{{ proftp_version }}' not in '{{ proftp_version_result.stdout }}') and (ansible_os_family == 'RedHat')"

- name: Installing ProFTPd Server...
  apt:
    pkg: proftpd
    state: present
  when: "('{{ proftp_version }}' not in '{{ proftp_version_result.stdout }}') and (ansible_os_family == 'Debian')"
 
- name: Installing ProFTPd Server...
  yum:
    pkg: proftpd
    state: present
  when: "('{{ proftp_version }}' not in '{{ proftp_version_result.stdout }}') and (ansible_os_family == 'RedHat')"

- name: Create Group proftp
  group:
    name: "{{ proftp_user_group }}"
    state: present

- name: Create proftp user
  user:
    name: "{{ proftp_user }}"
    createhome: no
    group: "{{ proftp_user_group }}"
    shell: /bin/false
    comment: "ProFTD Server User"
    state: present

- name: Deploy ProFTP configuration file
  template:
    src: proftpd.conf.j2
    dest: "{{ proftp_conf_path }}"
    force: yes

- name: Define user "proftp" and group "proftp" as the owner of configuration directory
  file:
    path: /etc/proftpd
    owner: "{{ proftp_user }}"
    group: "{{ proftp_user_group }}"
    recurse: yes

- name: Define owner, group and right on ProFTP configuration files
  file:
    path: "{{ item.path }}"
    force: "{{ item.force }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ proftp_conf_files }}"

- name: Add Iptables Input trafic rule for ProFTP
  command: >
   /sbin/iptables -t filter -A INPUT -i {{ network_interface }} -p tcp --dport {{ ftp_default_port }} -j ACCEPT -m comment --comment "TCP - ProFTP Server Input trafic"
  when: use_iptables_firewall

- name: Add Iptables Output trafic rule for ProFTP
  command: >
   /sbin/iptables -t filter -A OUTPUT -o {{ network_interface }} -p tcp --dport {{ ftp_default_port }} -j ACCEPT -m comment --comment "TCP - ProFTP Server Output trafic"
  when: use_iptables_firewall

- name: Add Iptables Input trafic rule for ProFTP passive ports
  command: >
   /sbin/iptables -t filter -A INPUT -i {{ network_interface }} -p tcp --dport {{ firwall_ftp_min_passive_port }}:{{ firwall_ftp_max_passive_port }} -j ACCEPT -m comment --comment "TCP - ProFTP Server Input trafic - Passive ports"
  when: use_iptables_firewall

- name: Add Iptables Output trafic rule for ProFTP passive ports
  command: >
   /sbin/iptables -t filter -A OUTPUT -o {{ network_interface }} -p tcp --dport {{ firwall_ftp_min_passive_port }}:{{ firwall_ftp_max_passive_port }} -j ACCEPT -m comment --comment "TCP - ProFTP Server Output trafic - Passive ports"
  when: use_iptables_firewall

- name: Restart ProFTP
  command: echo "Restart ProFTP service..."
  notify:
    - Restart ProFTP