---
# tasks file for proftp

# TODO
# 1 - Add more configuration to protect ProFTP (inspiration by BSL)

- name: Check if ProFTP is installed on the system
  shell: proftpd --version
  register: proftp_version_result
  ignore_errors: True

- name: Install ProFTPd Server.
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - "proftpd"
    - "proftpd-basic"
  when: ((proftp_version_result|failed) or (proftp_version_result.stdout.find('{{ proftp_version }}') != -1))

- name: Create Group proftp
  group:
    name: "{{ proftp_group }}"
    state: present

- name: Create proftp user
  user:
    name: "{{ proftp_user }}"
    createhome: no
    group: "{{ proftp_group }}"
    shell: /bin/false
    comment: "ProFTD Server User"
    state: present

- name: Deploy ProFTP configuration file
  template:
    src: proftpd.conf.j2
    dest: "{{ proftp_conf_path }}"

- name: Define user "proftp" and group "proftp" as the owner of configuration directory
  file:
    path: /etc/proftpd
    owner: "{{ proftp_user }}"
    group: "{{ proftp_group }}"
    recurse: yes

- name: Define owner, group and right on ProFTP configuration files
  file:
    path: "{{ item }}"
    owner: "{{ proftp_user }}"
    group: "{{ proftp_group }}"
    mode: "0644"
  with_items: 
    - "{{ proftp_modules_conf_path }}"
    - "{{ proftp_conf_path }}"

- name: Define owner, group and right on ProFTP TLS configuration files
  file:
    path: "{{ item.path }}"
    owner: "{{ proftp_user }}"
    group: "{{ proftp_group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ proftp_tls_files }}"
  when: proftp_tls_enabled

- name: Add Iptables rules for ProFTP
  include: iptables.yml
  when: proftp_iptables_enabled
  
- name: Restart ProFTP
  command: echo "Restart ProFTP service"
  notify:
    - Restart ProFTP

- meta: flush_handlers
  when: proftp_goss_enabled

- name: Test with goss
  include: goss.yml
  when: proftp_goss_enabled