---

- name: Copy goss tests file
  template:
    src: goss.j2
    dest: "/etc/proftpd/goss.yml"
    owner: root
    group: root
    mode: 0640

- name: Launch goss test
  goss:
    path: "/etc/proftpd/goss.yml"
    format: json

- name: Remove goss test
  file:
    path: "/etc/proftpd/goss.yml"
    state: absent