---
# This playbook contains ProFTP installation.
  
- name: Purge ProFTPd Server package if present
  apt: 
    pkg: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - "proftpd"
    - "proftpd-basic"
    
- name: Install ProFTPd Server package
  apt: 
    pkg: proftpd 
    state: present
  
- name: Restart ProFTP
  command: echo "Restart ProFTP service..."
  notify: 
    - Restart ProFTP