---
# This playbook contains ProFTP installation.

- name: Check if proftpd user group is on the system
  shell: getent group {{ proftpd_user_group }}
  register: proftpd_user_group_exists
  ignore_errors: True
  
- name: Create Group proftpd user group if not exists 
  group: name={{ proftpd_user_group }} state=present
  when: proftpd_user_group_exists.rc|int != 0

- name: Check if proftpd user is on the system
  shell: id {{ proftpd_user }}
  register: proftpd_user_exists
  ignore_errors: true
  
- name: Create proftpd user if not exists
  user: 
    name: "{{ proftpd_user }}"
    createhome: no 
    group: "{{ proftpd_user_group }}"
    shell: /bin/false 
    comment: "ProFTD Server User"
    state: present
  when: proftpd_user_exists.rc|int != 0

- name: Delete old init script and configurations directory if present
  file: 
    path: "{{item}}"
    state: absent
  with_items: 
    - "/etc/init.d/proftpd"
    - "/etc/proftpd"
  
- name: Purge ProFTPd Server package if present
  apt: 
    pkg: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - "proftpd"
    - "proftpd-basic"
    
- name: Install ProFTPd Server package
  apt: 
    pkg: proftpd 
    state: present

- name: Create ProFTP SSL configuration directory.
  file: 
    path: "{{ proftpd_ssl_conf_dir }}"
    state: directory
    owner: "{{ proftpd_user }}"
    group: "{{ proftpd_user_group }}"
  when: "{{ proftpd_enable_tls }}"
    
- name: Deploy SSL Certification Authority (CA) configuration file
  template: 
    src: openssl.conf.j2 
    dest: "{{ proftpd_ssl_config_file }}"
    force: yes
  when: "{{ proftpd_enable_tls }}"

- name: Generate SSL files( Key & certificat).
  shell: openssl req -new -x509 -nodes -days 3650 -subj "{{ proftpd_ssl_subj }}" -config {{ proftpd_ssl_config_file }} -extensions v3_req -out {{ proftpd_ssl_cert_file }} -keyout {{ proftpd_ssl_key_file }}
  when: "{{ proftpd_enable_tls }}"

- name: Secure private key file
  file: 
    path: "{{ proftpd_ssl_key_file }}"
    mode: 0400
  when: "{{ proftpd_enable_tls }}"

- name: Deploy TLS configuration file
  template: 
    src: tls.conf.j2 
    dest: "{{ proftpd_tls_conf_path }}"
    force: yes
  when: "{{ proftpd_enable_tls }}"
  
- name: Deploy ProFTP configuration file
  template: 
    src: proftpd.conf.j2
    dest: "{{ proftpd_conf_path }}"
    force: yes

- name: Define user "proftpd" and group "proftpd" as the owner of configuration directory
  sudo: yes
  file:
    path: /etc/proftpd
    owner: "{{ proftpd_user }}"
    group: "{{ proftpd_user_group }}"
    recurse: yes
    
- name: Define owner, group and right on ProFTP configuration files
  file: 
    path: "{{ item.path }}"
    force: "{{ item.force }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  when: "{{ item.when }}"
  with_items: "{{ proftpd_conf_files }}"
  
  

  
- name: Restart ProFTP
  command: echo "Restart ProFTP service..."
  notify: 
    - Restart ProFTP 