---
# This playbook contains APR plays that will be run on web server node (Apache and/or Apache Tomcat).

- name: Install Apr
  apt: pkg=libapr1 state=present
  
- name: Install Apr-dev
  apt: pkg=libapr1-dev state=present