---
- name: Copy goss tests file
  template:
      src: goss.j2
      dest: /etc/goss-apache.yml
      owner: root
      group: root
      mode: 0640

- name: Launch goss test
  goss:
    path: /etc/goss-apache.yml
    format: json

- name: Remove goss test file
  file:
    path: /etc/goss-apache.yml
    state: absent