---
# tasks file for iptable on ssh

- name: Add Iptables Input trafic rule for SSH
  iptables:
    action: insert
    chain: INPUT
    protocol: tcp
    ctstate: NEW,ESTABLISHED
    in_interface: "{{ ssh_network_interface }}"
    destination_port: "{{ ssh_config_port }}"
    jump: ACCEPT
    state: present
    comment: "TCP - OpenSSH Server Input trafic"

- name: Add Iptables Output trafic rule for SSH
  iptables:
    action: insert
    chain: OUTPUT
    protocol: tcp
    ctstate: NEW,ESTABLISHED
    out_interface: "{{ ssh_network_interface }}"
    source_port: "{{ ssh_config_port }}"
    jump: ACCEPT
    state: present
    comment: "TCP - OpenSSH Server Output trafic"