---
# tasks file for ssh

# First step - Secure environnment
- name : make a backup for file
  copy:
    src: "{{ item }}"
    dest: "{{ item }}.original"
    owner: root
    group: root
    mode: 0644
 with_items : "{{ backup_files }}"

- name : Init banner file with minimum informations
  command: echo "{{ banner_information }}" > "{{ item.src }}"
  with_items:  "{{ backup_files }}"

- name : Init motd file with warning message
  copy:
    src: motd
    dest: "{{ motd_file }}"
    owner: root
    group: root
    mode: 0644

- name : Init timeout for unactive user
  blockinfile:
    dest: "{{ profile_file }}"
    backup: yes
    insertafter: EOF
    block: |
        TMOUT={{ timeout }}
        HISTFILESIZE={{ histfilesize }}
        HISTSIZE={{ histsize }}
        export TMOUT HISTFILESIZE HISTSIZE
    owner: root
    group: root
    mode: 0644
    validate: 'source %s'


- name: Install sudo package
  apt:
    pkg: openssh-server
    state: present
  when: ansible_os_family == "Debian"
  
- name: Change the banner

- name: Change the config of SSH