---

# https://www.ssi.gouv.fr/uploads/2014/01/NT_OpenSSH.pdf - Rule R3
- name: Desinstall obsolete package
  apt:
    pkg: "{{ item }}""
    state: absent
  whith_items :
    - "telnet"
    - "rshd"
    - "rlogin"
    