---
# defaults file for apache_private_ca

root_user: root
root_group: sys
apache_home: /opt/apache2
apache_conf_dir: "{{ apache_home }}/conf"
apache_ssl_ca_bits: 2048
apache_ssl_ca_md: sha256
apache_ssl_ca_conf_dir: "{{ apache_conf_dir }}/ssl/ca"
apache_ssl_ca_key: "{{ apache_ssl_ca_conf_dir }}/ca_key.pem"
apache_ssl_ca_cert: "{{ apache_ssl_ca_conf_dir }}/ca_cert.pem"
apache_ssl_ca_default_days: 3650
apache_ssl_ca_country: FR
apache_ssl_ca_state: Rhone
apache_ssl_ca_locality: Lyon
apache_ssl_ca_organisation: Syscom
apache_ssl_ca_organisation_unit: IT
apache_ssl_ca_name: Authority Company Inc,
apache_ssl_ca_subj: "/C=\"{{ apache_ssl_ca_country }}\"/ST=\"{{ apache_ssl_ca_state }}\"/L=\"{{ apache_ssl_ca_locality }}\"/O=\"{{ apache_ssl_ca_organisation }}\"/OU=\"{{ apache_ssl_ca_organisation_unit }}\"/CN={{ apache_ssl_ca_name }}"