---
# tasks file for tomcat_apps

- name: Stop Tomcat service
  service:
    name: tomcat
    state: stopped
  ignore_errors: true

- name: Delete webapps contain
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "{{ tomcat_apps_webapps_directory }}/*"
    
3 - Télécharger le .war et le déposer dans le sous-repertoire webapps de Tomcat.
- name: Déployer l application
  get_url:
    url: "{{ tomcat_apps_nexus_maven_api }}?r={{ tomcat_apps_nexus_repository }}&g={{ tomcat_apps_groupId }}&a={{ tomcat_apps_artifactId }}&v={{ tomcat_apps_version }}&p={{ tomcat_apps_package }}"
    dest: "{{ tomcat_apps_webapps_directory }}/ROOT.war"
    mode: 0755


2 - Préparer tous les fichiers de configurations et les fichiers properties dans les bons repertoires


5 - Lancer Tomcat
Context.xml doit etre un template
il va contenir la configuration sécurisée de la bdd
il sera copié dans catalina_home>/conf/Catalina/localhost/ et son nom sera celui de l''application posée dans l''application