---
java_version: 1.8.0_73
#java_version: 1.7.0_79
jdk_versions: /opt/jdk_versions
jdk_last_version: "{{ jdk_versions }}/jdk{{ java_version }}"
jdk_tarball_name_32: jdk-8u73-linux-i586.tar.gz
jdk_tarball_name_64: jdk-8u73-linux-x64.tar.gz
os_32: 32
os_64: 64
jdk_32_url: "{{ nexus_repository }}/service/local/repositories/thirdparty/content/com/oracle/jdk/{{ java_version }}/jdk-{{ java_version }}-{{ os_32 }}.tar.gz"
jdk_64_url: "{{ nexus_repository }}/service/local/repositories/thirdparty/content/com/oracle/jdk/{{ java_version }}/jdk-{{ java_version }}-{{ os_64 }}.tar.gz"