---
- name: Change files in CATALINA_HOME/conf to be read & execute (0500)
  file:
    path: "{{ tomcat_last_version }}/conf"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user_group }}"
    mode: 0500
    recurse: yes

- name: Change directory CATALINA_HOME/logs (0300) for tomat user
  file:
    path: "{{ tomcat_last_version }}/logs"
    mode: 0300
    recurse: yes

- name: Delete unused files or directories
  file:
    path: "{{ tomcat_last_version }}/{{ item.path }}"
    state: absent
  with_items: "{{ tomcat_remove_files }}"

- name: Delete script *.bat files. We don't need them on Linux plateform
  command: rm {{ tomcat_last_version }}/bin/*.bat
  ignore_errors: true
  
- name: Create tomcat server info directory
  file:
    path: "{{ tomcat_last_version }}/lib/{{tomcat_server_info_dir}}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user_group }}"
    state: directory

- name: Remove version string from HTTP error messages
  template:
    src: "ServerInfo.properties.j2"
    dest: "{{ tomcat_last_version }}/lib/{{tomcat_server_info_dir}}/ServerInfo.properties"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user_group }}"

- name: Restart tomcat
  command: echo "Restart Tomcat service..."
  notify: 
    - Restart tomcat
  
# Remove version string from HTTP error messages by repacking CATALINA_HOME/server/lib/catalina.jar
#- name: Remove version string from HTTP error messages by repacking CATALINA_HOME/server/lib/catalina.jar
  #shell: cd "{{ tomcat_last_version }}/lib" && jar xf catalina.jar org/apache/catalina/util/ServerInfo.properties && sed -i 's/server.info.*/server.info=Apache Tomcat/' org/apache/catalina/util/ServerInfo.properties && jar uf catalina.jar org/apache/catalina/util/ServerInfo.properties && rm -rf "{{ tomcat_last_version }}/lib/org"