serv1 ansible_host=localhost ansible_connection=local ansible_become_pass="{{ serv1_become_password }}"
serv2 ansible_host=st-db-villeurbanne ansible_connection=ssh ansible_become_pass="{{ serv2_become_password }}"

[all]
#serv1
serv2

[dbserver]
serv1

[tomcat]
serv2

[apache]
#serv1

[proftp]
serv2