---
proftp_version: "1.3.5"
proftp_user: "proftpd"
proftp_user_group: "proftpd"
proftp_server_name: "Syscom FTP Server"
proftp_type_conf: "standalone"
proftp_transfert_log_file: "/var/log/proftpd/xferlog"
proftp_system_log_file: "/var/log/proftpd/proftpd.log"
proftp_conf_path: "/etc/proftpd/proftpd.conf"
proftp_modules_conf_path: "/etc/proftpd/modules.conf"
ftp_default_port: 21
firwall_ftp_min_passive_port: 5000
firwall_ftp_max_passive_port: 5100