---
# variables for postgresql_instance

dbs:
  - { db_user: 'apps', db_password: 'apps', db_user_roles: 'CREATEROLE CREATEUSER',  db_name: 'apps', db_schema: 'apps' }
  - { db_user: 'apps1', db_password: 'apps1', db_user_roles: 'CREATEROLE CREATEUSER',  db_name: 'apps1', db_schema: 'apps1' }
