---
# tasks file for portsentry

- name: Installing portsentry...
  apt:
    pkg: portsentry
    state: present
  when: ansible_os_family == 'Debian'

- name: Installing portsentry...
  yum:
    name: portsentry
    state: present
  when: ansible_os_family == 'RedHat'

- name: Copy portsentry.ignore IP address configuration file
  template:
    src: portsentry.ignore.j2
    dest: "{{ portsentry_ignore_file }}"
    owner: root
    group: root
    force: yes
    backup: yes

- name: Copy notification script
  template:
    src: notification.sh.j2
    dest: "{{ portsentry_notification_script }}"
    owner: root
    group: root
    force: yes

- name: Copy portsentry.conf configuration file
  template:
    src: portsentry.conf.j2
    dest: "{{ portsentry_config_file }}"
    owner: root
    group: root
    force: yes
    backup: yes

- name: Restart portsentry
  command: echo "Restart portsentry..."
  notify:
    - Restart portsentry