---
# tasks file for portsentry


- name: Installing portsentry
  apt:
    pkg: "{{ porsentry_package }}"
    state: present

- name: Copy porsentry configuration files
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    force: yes
    owner: root
    group: root
    mode: "{{item.mode}}"
  with_items:
   - "{{ portsentry_files }}"

- name: Restart portsentry
  command: echo "Restart portsentry..."
  notify:
    - Restart portsentry

- name: Test with goss
  include: goss.yml
  when: portsentry_goss_enabled