---
# tasks file for portsentry


- name: Installing portsentry...
  apt:
    pkg: portsentry
    state: present

- name: Copy porsentry configuration files
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    force: yes
    owner: root
    group: root
    mode: "{{item.mode}}"
  with_items:
   - "{{ portsentry_files }}"

- name: Restart portsentry
  command: echo "Restart portsentry..."
  notify:
    - Restart portsentry