---
# tasks file for monit_tomcat
- name: Copy configuration file
  template:
    backup: yes
    src: tomcat.conf.j2
    dest: "{{ monit_tomcat_config_file }}"
    owner: root
    group: root
    mode: 0644

- name: Reload monit
  command: echo "Reload monit..."
  notify:
    - Reload monit
