---
- name: Copy goss tests file
  template:
      src: goss.j2
      dest: /etc/goss-firewall.yml
      owner: root
      group: root
      mode: 0640
- name: Launch goss test
  goss:
    path: /etc/goss-firewall.yml
    format: json
    output_file : /etc/goss-firewall.json