---
# This playbook contains firewall plays that will be run on all nodes.

- name: Stop firewall script and disable it.
  service:
    name: firewall
    state: stopped
    enabled: no
  ignore_errors: true

- name: Installing iptables package...
  apt:
    pkg: iptables
    state: present
  when: ansible_os_family == 'Debian'

- name: Installing iptables package...
  yum:
    name: iptables
    state: present
  when: ansible_os_family == 'RedHat'

- name: Copy firewall files into directories
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    force: "{{item.force}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
    mode: "{{item.mode}}"
  with_items:
   - "{{ firewall_script_files }}"

- name: Enable firewall
  service:
    name: firewall
    enabled: yes
    state: started