---
# This playbook contains firewall plays that will be run on all nodes.

   
# Install iptables if this package was absent
- name: Install iptables if this package was absent
  apt: pkg=openssl state=present
  ignore_errors: true

# Stop eventual firewall service runing
- name: Stop eventual firewall service runing
  service: name=firewall state=stopped enabled=no
  ignore_errors: true

# Remove eventual firewall from boot service
- name: Remove eventual firewall from boot service
  shell: insserv -r firewall
  ignore_errors: true

# Copy firewall files into directories
- name: Copy firewall files into directories
  template: src={{item.src}} dest={{item.dest}} force={{item.force}} owner={{item.owner}} group={{item.group}} mode={{item.mode}}   
  with_items:
   - "{{ firewall_script_files }}"

# Enable/Start firewall
- name: Enable/Start firewall
  service: name=firewall state=started enabled=yes
  
  

  


