---
# tasks file for monit

- name: Install monit package
  apt:
    pkg: monit
    state: present

- name: Copy configuration file
  template:
    backup: yes
    src: monit.conf.j2
    dest: "{{ monit_config_file }}"
    
- name : Iptables rules
  include: iptables.yml
  when: monit_activate_admin_dashboard and iptables_enabled

#- name: Reload monit
  #command: echo "Reload monit..."
  #notify:
    #- Reload monit