---
tomcat_init_script: /etc/init.d/tomcat
tomcat_conf_files:
 - { src: 'server.xml.j2', dest: '{{ tomcat_last_version }}/conf/server.xml', force: yes }
 - { src: 'setenv.sh.j2', dest: '{{ tomcat_last_version }}/bin/setenv.sh', force: yes }
 - { src: 'web.xml.j2', dest: '{{ tomcat_last_version }}/conf/web.xml', force: yes }
 - { src: 'logging.properties.j2', dest: '{{ tomcat_last_version }}/conf/logging.properties', force: yes }
