---
# tasks file for ntp

- name: Installing NTP...
  apt:
    name: ntp
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Installing NTP...
  yum:
    name: ntp
    state: present
    update_cache: yes
  when: ansible_os_family == 'RedHat'

- name: Add Iptables Input trafic rule for NTP
  command: >
   /sbin/iptables -t filter -A INPUT -i {{ network_interface }} -p udp --dport 123 -j ACCEPT -m comment --comment "UDP - NTP Server Input trafic"
  when: use_iptables_firewall

- name: Add Iptables Output trafic rule for NTP
  command: >
   /sbin/iptables -t filter -A OUTPUT -o {{ network_interface }} -p udp --dport 123 -j ACCEPT -m comment --comment "UDP - NTP Server Output trafic"
  when: use_iptables_firewall

- name: Start the ntp service
  service:
    name: ntp
    state: started
    enabled: true