---  
- name: Deploy configurations files
  template: 
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    force: "{{item.force}}"
  with_items:
   - "{{ postgres_conf_files }}"
   
#- name: Alter user postgres password
  #shell: su - postgres /bin/bash -c  "psql -c \"ALTER USER postgres WITH PASSWORD '{{ postgres_user_password }}';\""

- name: Enable/Start PostgreSQL Server
  service: name=postgresql enabled=yes
  
- name: Restart PostgreSQL
  command: echo "Restart PostgreSQL..."
  notify: 
    - Restart PostgreSQL