---
- name: Deploy configurations files
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    force: "{{item.force}}"
  with_items:
   - "{{ postgres_conf_files }}"

- name: Allow access to postgres port through firewall
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items: "{{ firewallports }}"
  when: use_ufw_firewall
  
- name: Enable/Start PostgreSQL Server
  service:
    name: postgresql
    enabled: yes

- name: Restart PostgreSQL
  command: echo "Restart PostgreSQL"
  notify:
    - Restart PostgreSQL