---

- name: Add Iptables Input trafic rule for sonarqube
  become: true
  iptables:
    action: insert
    chain: INPUT
    protocol: tcp
    ctstate: NEW,ESTABLISHED
    match: tcp
    in_interface: "{{ sonarqube_network_interface }}"
    destination_port: "{{ sonarqube_web_port }}"
    jump: ACCEPT
    state: present
    comment: "TCP - Sonarqube Input trafic"