---

# Postgres behind iptables firewall : Look at https://www.digitalocean.com/community/tutorials/iptables-essentials-common-firewall-rules-and-commands
- name: Add Iptables Input trafic rule for Postgres
  command: >
   /sbin/iptables -t filter -A INPUT -i {{ network_interface }} -p tcp --dport {{ postgres_port }} -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT -m comment --comment "TCP - Postgres Server Input trafic"

- name: Add Iptables Output trafic rule for Postgres
  command: >
   /sbin/iptables -t filter -A OUTPUT -o {{ network_interface }} -p tcp --sport {{ postgres_port }} -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT -m comment --comment "TCP - Postgres Server Output trafic"