---
- name: Check if postgresql is installed on the system
  shell: aptitude search {{ postgres_server_pkg }} || echo "Unknown PostgreSQL Server"
  register: postgresql_exists

- name: Installing PostgreSQL Server...
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - "{{ postgres_server_pkg }}"
    - "{{ postgres_client_pkg }}"

- name: Deploy configurations files
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    force: yes
    backup: yes
  with_items:
   - "{{ postgres_conf_files }}"

# Postgres behind iptables firewall : Look at https://www.digitalocean.com/community/tutorials/iptables-essentials-common-firewall-rules-and-commands
- name: Add Iptables Input trafic rule for Postgres
  command: >
   /sbin/iptables -t filter -A INPUT -i {{ network_interface }} -p tcp --dport {{ postgres_port }} -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT -m comment --comment "TCP - Postgres Server Input trafic"
  when: use_iptables_firewall

- name: Add Iptables Output trafic rule for Postgres
  command: >
   /sbin/iptables -t filter -A OUTPUT -o {{ network_interface }} -p tcp --sport {{ postgres_port }} -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT -m comment --comment "TCP - Postgres Server Output trafic"
  when: use_iptables_firewall

- name: Restart PostgreSQL
  command: echo "Restart PostgreSQL"
  notify:
    - Restart PostgreSQL