---
# tasks file for postgres

- name: Check if postgresql is installed on the system
  shell: aptitude search {{ postgres_server_pkg }} || echo "Unknown PostgreSQL Server"
  register: postgresql_exists

- name: Installing PostgreSQL Server...
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - "{{ postgres_server_pkg }}"
    - "{{ postgres_client_pkg }}"

- name: Deploy configurations files
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    force: yes
  with_items:
   - "{{ postgres_conf_files }}"

- name: Add Iptables rule
  include: iptables.yml
  when: iptables_enabled

- name: Restart PostgreSQL
  command: echo "Restart PostgreSQL"
  notify:
    - Restart PostgreSQL