---
- name: Check if postgresql is installed on the system
  shell: aptitude search {{ postgres_server_pkg }} || echo "Unknown PostgreSQL Server"
  register: postgresql_exists

- name: Install PostgreSQL Server
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - "{{ postgres_server_pkg }}"
    - "{{ postgres_client_pkg }}"
  when: "'{{ postgres_server_pkg }}' not in '{{ postgresql_exists.stdout }}'"