---
# tasks file for postgres

- name: Installing PostgreSQL Server...
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - "{{ postgres_server_pkg }}"
    - "{{ postgres_client_pkg }}"

- name: Change the config of pg_hba.conf
  lineinfile: 
    dest: "{{ postgres_pg_hba_file }}" 
    regexp: "{{ item.regexp }}" 
    line: "{{ item.value }}"
    state: present
  with_items: "{{ postgres_pg_hba_directives }}"

- name: Change the config of postgresql.conf
  lineinfile: 
    dest: "{{ postgres_config_file }}" 
    regexp: "{{ item.regexp }}" 
    line: "{{ item.value }}"
    state: present
  with_items: "{{ postgres_config_directives }}"

- name: Add Iptables rule
  include: iptables.yml
  when: postgres_iptables_enabled

- name: Restart PostgreSQL
  command: echo "Restart PostgreSQL"
  notify:
    - Restart PostgreSQL

- meta: flush_handlers
  when: postgres_goss_enabled

- name: Test with goss
  include: goss.yml
  when: postgres_goss_enabled