---
# tasks file for sudo_users

- name: Install sudo package
  apt:
    pkg: sudo
    state: present
  when: ansible_os_family == "Debian"

  
- name: Create sudoers.d directory
  file:
    path: /etc/sudoers.d
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Set includedir in sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"
    
# 1 - Create user (name, first name, homedir, public & private key SSH) on host ansible machine.
- name: Create user on local machine (Ansible host machine)
  local_action: user name={{ user_name }} comment={{ user_comment }} shell=/bin/bash generate_ssh_key=yes ssh_key_bits=2048
  #ssh_key_passphrase={{ user_key_passphrase }} 

# 2 - Create user on target server without public & private key SSH.
- name: Create user on servers machine 
  user:
    name: "{{ user_name }}"
    comment: "{{ user_comment }}"
    shell: /bin/bash
    generate_ssh_key: no
 
# 1 - Create user (name, first name, homedir, public & private key SSH) on host ansible machine.
- name: Create user on local machine (Ansible host machine)
  local_action: shell cat /home/{{ user_name }}/.ssh/id_rsa.pub 
  register: user_public_key

- name: Export public keys to servers
  lineinfile:
    dest: "/home/{{ user_name }}/.ssh/authorized_keys"
    create: yes
    state: present
    mode: 0600
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    line: '{{ user_public_key.stdout }}'
    

# 3 - Add user to sudoers group
- name: Create sudoers
  lineinfile:
    dest: "/etc/sudoers.d/sudoers.d.{{ user_name }}"
    create: yes
    state: present
    mode: 0440
    owner: root
    group: root
    line: '{{ user_name }} ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

  