---
# tasks file for sudo_users

- name: Install required librairies
  apt:
    pkg: sudo
    state: present
  when: ansible_os_family == "Debian"

  
- name: Create sudoers.d directory
  file:
    path: /etc/sudoers.d
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Set includedir in sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"

    
# 1 - Créer les utilisateurs avec leur nom, prenom, homedir,
- name: Create user
  user:
    name:
    comment:
    shell: /bin/bash
    generate_ssh_key: 
    ssh_key_bits: 
    
# 2 - Génrer leurs clés publiques/privés ssh avec mot de passe pour la clé privée

# 3 - ajouter les utilisateurs aux group sudoers
- name: Create sudoers
  template:
    src: sudoers.d.j2
    dest: "/etc/sudoers.d/{{ sudoers_filename }}"
    mode: 0440
    owner: root
    group: root
    validate: "/usr/sbin/visudo -cf %s"
  when: not sudoers_remove

- name: Remove sudoers
  file:
    path: "/etc/sudoers.d/{{ sudoers_filename }}"
    state: absent
  when: sudoers_remove
  